language: cpp
    
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh github_package testthat
  - ./travis-tool.sh github_package Rcpp11/Rcpp11
  - ./travis-tool.sh github_package Rcpp11/attributes
  - ./travis-tool.sh r_binary_install Rcpp
  - ./travis-tool.sh github_package RcppCore/RcppParallel
   
script:
  - Rscript testthat.R
  
notifications:
  email:
    on_success: change
    on_failure: change

